Repository YPM-Informatics/COPISClient, pull requests merged in 2021-05, with the labels that each got.

#105 Hotfix copis file and visual tweaks
  copis/config/actionScript.copis
  copis/config/test_path.copis
  copis/gl/actionvis.py
  copis/gl/glcanvas.py
  copis/gui/machine_settings_dialog.py
  copis/gui/main_frame.py
  copis/gui/panels/controller.py
  copis/gui/panels/machine_toolbar.py
  copis/gui/panels/properties.py
  copis/gui/panels/timeline.py
  copis/store.py
Labels: bug, enhancement

#106 Develop
  copis/config/actionScript.copis
  copis/config/test_path.copis
  copis/gl/actionvis.py
  copis/gl/glcanvas.py
  copis/gui/machine_settings_dialog.py
  copis/gui/main_frame.py
  copis/gui/panels/controller.py
  copis/gui/panels/machine_toolbar.py
  copis/gui/panels/properties.py
  copis/gui/panels/timeline.py
  copis/store.py
Labels: bug, enhancement

#107 Improve import style with relative imports
  copis/client.py
  copis/config.py
  copis/console.py
  copis/core.py
  copis/enums.py
  copis/gl/glcanvas.py
  copis/gui/main_frame.py
  copis/gui/panels/controller.py
  copis/pathutils.py
  copis/settings.py
  copis/store.py
  copisclient.py
Labels: enhancement

#109 Make Z-axis point up instead of Y-axis
  copis/core.py
  copis/gl/actionvis.py
  copis/gl/chamber.py
  copis/gl/glcanvas.py
  copis/gl/viewcube.py
  copis/gui/panels/pathgen_toolbar.py
  copis/gui/panels/properties.py
  copis/helpers.py
Labels: bug, enhancement

#110 Fix viewcube and typo in chamber.py
  copis/gl/chamber.py
  copis/gl/glcanvas.py
  copis/gl/viewcube.py
Labels: bug

#111 Change path divide to be along y-axis
  copis/gui/panels/pathgen_toolbar.py
Labels: bug

#112 Fix pan and tilt angles
  copis/gl/actionvis.py
  copis/gui/panels/pathgen_toolbar.py
  copis/helpers.py
Labels: bug

#113 Add checklist for selecting devices, improve pathgen dialogs, fix handsome dan model
  copis/gl/viewcube.py
  copis/gui/panels/pathgen_toolbar.py
  copis/gui/wxutils.py
  copis/helpers.py
  model/handsome_dan.obj
Labels: enhancement
